name: CI

on:
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: develop
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        BASE_BRANCH: develop
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
        CNAME: blog.qiuz.site
     
    - name: delete deploy branch
      run: git push --delete "https://${{ secrets.ACCESS_TOKEN }}@${{ secrets.GIT_REF }}" deploy
